image: docker
variables:
  CI_REGISTRY_IMAGE: "${CI_REGISTRY}/${CI_PROJECT_PATH}"

stages:
- build
- deploy-dev
- deploy-qa

build:
  stage: build
  tags:
  - bpm
  - dev
  artifacts:
    name: dist
    paths:
    - dist
    expire_in: 10 yrs
  only:
  - master
  script:
  - export JOB_CONTAINER_ID=$(docker ps -q -f "label=com.gitlab.gitlab-runner.job.id=${CI_JOB_ID}")
  - docker run --rm
    --privileged
    --volumes-from ${JOB_CONTAINER_ID}
    --volume /root/.ssh:/root/.ssh:ro
    -w $(pwd)
    node:11.9-alpine
    sh -c "npm install && npm run build"
  - docker build -t "${CI_REGISTRY_IMAGE}:${CI_PIPELINE_ID}" .
  - docker push "${CI_REGISTRY_IMAGE}:${CI_PIPELINE_ID}"

.deployment: &deployment
  image:
    name: docker/compose:1.23.1
    entrypoint: ["/bin/sh", "-c"]
  script:
  - docker-compose pull
  - docker-compose up -d --force-recreate
  
deploy-dev:
  stage: deploy-dev
  environment: DEV
  tags:
  - bpm
  - dev
  only:
  - master
  <<: *deployment

deploy-qa:
  stage: deploy-qa
  environment: QA
  tags:
  - bpm
  - qa
  only:
  - master
  <<: *deployment
